analyzer:
  errors:
    eol_at_end_of_file: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    sort_pub_dependencies: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false